[workspace]

members = [
    "amber",
    "amber_serialization",
    "amber_net",
    "amber_world",
    "amber_object",
    "amber_chat",
    "amber_mail",
    "amber_logging",
    "amber_cache",
    "amber_res",
    "amber_patch",
    "amber_audio",
    "amber_config",
]
